### ISSUE TITLE
upgrading bx-python to newer versions of python

### ISSUE THREAD

**Issue by adeslatt** [bxlab/bx-python#82]
Having some difficulty with dependencies in building a container for a package that depends upon bx-python.  Incompatible versions of python -- package requires python 3.8.5 and bx-python 
```bash
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - bx-python -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0']

Your python: defaults/osx-64::python==3.8.5=h26836e1_1

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.
```

Any chance for a fix ?

**Comment by nsoranzo** [comment]
Thanks for opening the issue. Since this is happening when installing bx-python via conda, the right place to open the issue is probably the repository for its conda recipe ( https://github.com/bioconda/bioconda-recipes/ I presume).
Any way, can you please provide the conda command that caused the issue for you?
